companies:
  - name: LÃ¤gg till!
    url: https://github.com/okfse/opendiversitydata
    twitter: 
    img: 
    diversitydata: No
    eeo-1: No
    dcat-ap: No
    documentation: <link to company's diversity data>
    date-updated:
    status: No
